### PR TITLE
Added whereLocale and whereLocales methods

### PR DESCRIPTION
**Pull request by ahmetbarut**
In some cases, there are times when I want to extract content according to the user's locale, and in this case, I found these solutions instead of constantly writing queries.

`whereLocale` and `whereLocales` methods.

```php
$post->whereLocale('title', 'en')->get();

// or mutliple locales
$post->whereLocales('title', ['en', 'fr'])->get();
```

### CODE REVIEW

**Comment by freekmurze** [comment]
Thanks, could you also mention these in the readme with a good example.

**Comment by ahmetbarut** [comment]
@freekmurze is this [here](https://github.com/spatie/.github/compare/main...ahmetbarut:.github:patch-1)?

**Comment by ahmetbarut** [comment]
@freekmurze I have attached documentation for both this pull request and the [previous](https://github.com/spatie/laravel-translatable/pull/361) pull request

**Review by ozgurtr — APPROVED** [review]

**Comment by freekmurze** [comment]
Thanks!

**Pull request merged**
