### PR TITLE
add setAttribute for stright storing values for translatable attribute

### PR DESCRIPTION
**Pull request by Astyk**
Sometimes need to use attribute assignment without known translations, ex. at model mass assignment very uncomfortable provide whole structure of translation object.

I try to patch Model::setAttribute method to overcome this issue

### CODE REVIEW

**Comment by freekmurze** [comment]
Hi, thanks for this.

Two remarks:
- could you remove that `var_export` from the code.
- could you add a test that proves your code works?

**Comment by Astyk** [comment]
Hi, thanks for review.
I'll try to write tests as soon as possible.

**Comment by freekmurze** [comment]
Cool, leave a comment here when you've added the test.

**Comment by freekmurze** [comment]
Open up the issue when you have some time to work further on this.

**Comment by Astyk** [comment]
Sorry,
And thank You for patience, I am really busy right now.

**Comment by freekmurze** [comment]
If you can't find that time, that's fine, really.

You are under no obligation whatsoever to finish this.

**Pull request closed without merging**
